# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=350)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Routes.Category')),
                ('City', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Routes.City')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')),
                ('City', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Routes.City')),
                ('Destiny', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Routes.Point')),
            ],
        ),
    ]
