# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='Destiny',
        ),
        migrations.AddField(
            model_name='point',
            name='Routes',
            field=models.ManyToManyField(to='Routes.Route'),
        ),
    ]
