# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0002_auto_20180605_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='Routes',
        ),
        migrations.AddField(
            model_name='route',
            name='Points',
            field=models.ManyToManyField(to='Routes.Point'),
        ),
    ]
