# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routes', '0003_auto_20180605_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
